"use server";

import { and, desc, eq, gte, isNull, sql } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireApiAdmin } from "@/lib/auth/current-user";
import { runAdminFormAction } from "@/lib/admin/form-errors";
import { db } from "@/lib/db";
import {
  aiUsage,
  assistantSettings,
  auditLogs,
  campaignMessages,
  companyLeads,
  inboxAccounts,
  inboxClassifications,
  inboxDrafts,
  inboxMessages,
  inboxThreads,
  leadEmailDrafts,
  notifications,
  outreachCampaigns,
  siteSettings,
  suppressedEmails,
  users,
} from "@/lib/db/schema";
import { AppError, NotFoundError } from "@/lib/errors";
import { enforceRateLimit, rateKey } from "@/lib/rate-limit";
import { assertSameOrigin } from "@/lib/security";
import { getEnv } from "@/lib/env";
import { getMailAccountCredentials } from "./mail-accounts";
import { getAiKnowledgeContext } from "./ai-context";
import { buildLeadDraftAiRequest, buildThreadAiRequest } from "./ai-prompts";
import { callAssistantAi } from "./ai-usage";
import { generateClassification, generateDraft } from "./ai-generation";
import { hasUnsafeDraftPromise, stripQuotedHistory } from "./ai-safety";
import { signUnsubscribeToken } from "./unsubscribe-token";
import { campaignActivationBlockReasons, outreachBusinessAddress } from "./campaign-rules";

async function aiActor() {
  await assertSameOrigin();
  const admin = await requireApiAdmin();
  await enforceRateLimit(rateKey("assistantAi", admin.id), { limit: 10, windowSeconds: 60 });
  return admin;
}

async function flagThread(threadId: string, title: string): Promise<void> {
  await db.update(inboxThreads).set({
    needsAttention: true,
    updatedAt: new Date(),
  }).where(eq(inboxThreads.id, threadId));
  const admins = await db.select({ id: users.id }).from(users)
    .where(and(eq(users.role, "admin"), eq(users.status, "active"), isNull(users.deletedAt)));
  for (const admin of admins) {
    await db.insert(notifications).values({
      userId: admin.id,
      type: "assistant_attention",
      title,
      body: "An AI result needs human review.",
      link: `/admin/assistant?thread=${threadId}`,
      metadata: { threadId },
    });
  }
}

function requestId(formData: FormData, field: string): string {
  const parsed = z.uuid().safeParse(formData.get(field));
  if (!parsed.success) throw new AppError(`Invalid ${field}.`, 422);
  return parsed.data;
}

async function classifyThreadImpl(formData: FormData): Promise<void> {
  const admin = await aiActor();
  const id = requestId(formData, "threadId");
  const [thread] = await db.select().from(inboxThreads)
    .where(eq(inboxThreads.id, id)).limit(1);
  if (!thread) throw new NotFoundError("Inbox thread not found.");
  const [latest] = await db.select().from(inboxMessages)
    .where(and(eq(inboxMessages.threadId, id), eq(inboxMessages.direction, "inbound")))
    .orderBy(desc(inboxMessages.sentAt), desc(inboxMessages.createdAt))
    .limit(1);
  if (!latest) throw new AppError("This thread has no inbound email to classify.", 422);

  const [settings] = await db.select().from(assistantSettings)
    .where(eq(assistantSettings.id, 1)).limit(1);
  const context = await getAiKnowledgeContext();
  const request = buildThreadAiRequest({
    purpose: "classify",
    emailText: stripQuotedHistory(latest.textBody).slice(0, 8_000),
    context: {
      ...context,
      businessDescription: settings?.businessDescription ?? null,
    },
  });
  let result;
  try {
    result = await generateClassification(
      { complete: (value) => callAssistantAi("thread_classification", value) },
      request,
    );
  } catch (error) {
    await flagThread(thread.id, "AI classification needs review");
    throw error;
  }
  const needsHuman = result.needs_human || result.confidence < 0.6;
  await db.transaction(async (tx) => {
    await tx.insert(inboxClassifications).values({
      threadId: thread.id,
      category: result.category,
      urgency: result.urgency,
      summary: result.summary,
      suggestedStatus: result.suggested_status,
      confidence: Math.round(result.confidence * 100),
      needsHuman,
      source: "ai",
    });
    await tx.update(inboxThreads).set({
      category: result.category,
      needsAttention: needsHuman || thread.needsAttention,
      updatedAt: new Date(),
    }).where(eq(inboxThreads.id, thread.id));
    await tx.insert(auditLogs).values({
      actorUserId: admin.id,
      actorRole: "admin",
      action: "assistant.ai_thread_classified",
      entityType: "inbox_thread",
      entityId: thread.id,
      description: "Thread classification generated by optional AI.",
      metadata: { category: result.category, confidence: result.confidence, needsHuman },
    });
  });
  if (needsHuman) await flagThread(thread.id, "AI classification needs human review");
  revalidatePath("/admin/assistant");
}

export async function classifyThreadWithAiAction(formData: FormData): Promise<void> {
  return runAdminFormAction("/admin/assistant", () => classifyThreadImpl(formData));
}

async function draftReplyImpl(formData: FormData): Promise<void> {
  const admin = await aiActor();
  const id = requestId(formData, "threadId");
  const [thread] = await db.select().from(inboxThreads)
    .where(eq(inboxThreads.id, id)).limit(1);
  if (!thread) throw new NotFoundError("Inbox thread not found.");
  const [latest] = await db.select().from(inboxMessages)
    .where(and(eq(inboxMessages.threadId, id), eq(inboxMessages.direction, "inbound")))
    .orderBy(desc(inboxMessages.sentAt), desc(inboxMessages.createdAt))
    .limit(1);
  if (!latest) throw new AppError("This thread has no inbound email to draft a reply to.", 422);
  const [settings] = await db.select().from(assistantSettings)
    .where(eq(assistantSettings.id, 1)).limit(1);
  const context = await getAiKnowledgeContext();
  const request = buildThreadAiRequest({
    purpose: "draft_reply",
    emailText: stripQuotedHistory(latest.textBody).slice(0, 8_000),
    context: { ...context, businessDescription: settings?.businessDescription ?? null },
  });
  let result;
  try {
    result = await generateDraft(
      { complete: (value) => callAssistantAi("thread_reply_draft", value) },
      request,
    );
  } catch (error) {
    await flagThread(thread.id, "AI reply draft needs review");
    throw error;
  }
  const body = [result.draft, settings?.signatureText?.trim()].filter(Boolean).join("\n\n");
  if (hasUnsafeDraftPromise(body)) {
    await flagThread(thread.id, "AI reply draft needs review");
    throw new AppError("AI draft was rejected because it contains an unsafe promise.", 422, "ai_unsafe_output");
  }
  await db.transaction(async (tx) => {
    await tx.insert(inboxDrafts).values({
      threadId: thread.id,
      accountId: thread.accountId,
      body,
      source: "ai",
      createdByUserId: admin.id,
    });
    if (result.needs_human) {
      await tx.update(inboxThreads).set({ needsAttention: true, updatedAt: new Date() })
        .where(eq(inboxThreads.id, thread.id));
    }
    await tx.insert(auditLogs).values({
      actorUserId: admin.id,
      actorRole: "admin",
      action: "assistant.ai_reply_drafted",
      entityType: "inbox_thread",
      entityId: thread.id,
      description: "AI-generated reply saved as an unsent draft.",
      metadata: { needsHuman: result.needs_human },
    });
  });
  if (result.needs_human) await flagThread(thread.id, "AI reply draft needs human review");
  revalidatePath("/admin/assistant");
}

export async function draftReplyWithAiAction(formData: FormData): Promise<void> {
  return runAdminFormAction("/admin/assistant", () => draftReplyImpl(formData));
}

async function draftLeadEmailImpl(formData: FormData): Promise<void> {
  const admin = await aiActor();
  const leadId = requestId(formData, "leadId");
  const accountId = z.enum(["support", "gmail"]).safeParse(formData.get("accountId"));
  if (!accountId.success) throw new AppError("Choose a valid sender account.", 422);
  const account = getMailAccountCredentials().find((item) => item.id === accountId.data);
  if (!account) throw new AppError(`The ${accountId.data} sender account is not configured.`, 503);
  const [lead] = await db.select({
    id: companyLeads.id,
    company: companyLeads.company,
    contactName: companyLeads.contactName,
    designation: companyLeads.designation,
    city: companyLeads.city,
    industry: companyLeads.industry,
    website: companyLeads.website,
  }).from(companyLeads).where(eq(companyLeads.id, leadId)).limit(1);
  if (!lead) throw new NotFoundError("Lead not found.");
  const [settings] = await db.select().from(assistantSettings)
    .where(eq(assistantSettings.id, 1)).limit(1);
  const context = await getAiKnowledgeContext();
  const request = buildLeadDraftAiRequest({
    lead,
    context: { ...context, businessDescription: settings?.businessDescription ?? null },
  });
  let result;
  try {
    result = await generateDraft(
      { complete: (value) => callAssistantAi("lead_first_email_draft", value) },
      request,
    );
  } catch (error) {
    await db.insert(auditLogs).values({
      actorUserId: admin.id,
      actorRole: "admin",
      action: "assistant.ai_lead_draft_rejected",
      entityType: "company_lead",
      entityId: lead.id,
      description: "AI lead draft output was rejected by validation.",
    });
    throw error;
  }
  const [existingAddress] = await db.select({
    email: companyLeads.email,
    contactName: companyLeads.contactName,
  }).from(companyLeads).where(eq(companyLeads.id, lead.id)).limit(1);
  if (!existingAddress) throw new NotFoundError("Lead not found.");
  const token = signUnsubscribeToken(existingAddress.email, getEnv().SESSION_SECRET);
  const unsubscribeUrl = `${getEnv().APP_URL.replace(/\/+$/, "")}/api/unsubscribe/${token}`;
  let body = result.draft.replaceAll("{{unsubscribe_url}}", unsubscribeUrl);
  if (!/unsubscribe|opt[ -]?out/i.test(body)) {
    body += `\n\nTo stop receiving outreach, unsubscribe here: ${unsubscribeUrl}`;
  }
  if (settings?.signatureText?.trim()) body += `\n\n${settings.signatureText.trim()}`;
  if (hasUnsafeDraftPromise(body)) {
    throw new AppError("AI draft was rejected because it contains an unsafe promise.", 422, "ai_unsafe_output");
  }

  await db.insert(inboxAccounts).values({ id: accountId.data }).onConflictDoNothing();
  const [draft] = await db.insert(leadEmailDrafts).values({
    leadId: lead.id,
    accountId: accountId.data,
    subject: `A note for ${lead.company}`.slice(0, 998),
    body,
    source: "ai",
    status: "draft",
    createdByUserId: admin.id,
  }).returning({ id: leadEmailDrafts.id });
  if (!draft) throw new Error("AI lead email draft could not be saved.");
  await db.insert(auditLogs).values({
    actorUserId: admin.id,
    actorRole: "admin",
    action: "assistant.ai_lead_draft_saved",
    entityType: "lead_email_draft",
    entityId: draft.id,
    description: "AI-generated first email saved as a draft; no message was sent.",
    metadata: { leadId: lead.id, accountId: accountId.data, needsHuman: result.needs_human },
  });
  if (result.needs_human) {
    const admins = await db.select({ id: users.id }).from(users)
      .where(and(eq(users.role, "admin"), eq(users.status, "active"), isNull(users.deletedAt)));
    for (const recipient of admins) {
      await db.insert(notifications).values({
        userId: recipient.id,
        type: "assistant_attention",
        title: "AI lead draft needs human review",
        body: `Review the first-email draft for ${lead.company.slice(0, 120)}.`,
        link: `/admin/assistant/leads?edit=${lead.id}`,
        metadata: { leadId: lead.id, draftId: draft.id },
      });
    }
  }
  revalidatePath("/admin/assistant/leads");
}

export async function draftLeadEmailWithAiAction(formData: FormData): Promise<void> {
  return runAdminFormAction("/admin/assistant/leads", () => draftLeadEmailImpl(formData));
}

async function updateLeadDraftImpl(formData: FormData): Promise<void> {
  const admin = await aiActor();
  const parsed = z.object({
    id: z.uuid(),
    subject: z.string().trim().min(1).max(998),
    body: z.string().trim().min(1).max(20_000),
  }).safeParse({
    id: formData.get("draftId"),
    subject: formData.get("subject"),
    body: formData.get("body"),
  });
  if (!parsed.success) throw new AppError(parsed.error.issues[0]?.message ?? "Invalid lead draft.", 422);
  if (hasUnsafeDraftPromise(parsed.data.body)) {
    throw new AppError("Remove unsupported promises before saving this draft.", 422, "ai_unsafe_output");
  }
  const [updated] = await db.update(leadEmailDrafts).set({
    subject: parsed.data.subject,
    body: parsed.data.body,
    updatedAt: new Date(),
  }).where(and(eq(leadEmailDrafts.id, parsed.data.id), eq(leadEmailDrafts.status, "draft")))
    .returning({ id: leadEmailDrafts.id, leadId: leadEmailDrafts.leadId });
  if (!updated) throw new NotFoundError("Editable lead draft not found.");
  await db.insert(auditLogs).values({
    actorUserId: admin.id,
    actorRole: "admin",
    action: "assistant.lead_draft_edited",
    entityType: "lead_email_draft",
    entityId: updated.id,
    description: "Lead email draft reviewed and edited by an administrator.",
  });
  revalidatePath("/admin/assistant/leads");
}

export async function updateLeadEmailDraftAction(formData: FormData): Promise<void> {
  return runAdminFormAction("/admin/assistant/leads", () => updateLeadDraftImpl(formData));
}

async function approveLeadDraftImpl(formData: FormData): Promise<void> {
  const admin = await aiActor();
  const draftId = requestId(formData, "draftId");
  const [draft] = await db.select().from(leadEmailDrafts)
    .where(and(eq(leadEmailDrafts.id, draftId), eq(leadEmailDrafts.status, "draft")))
    .limit(1);
  if (!draft) throw new NotFoundError("Unsent lead draft not found.");
  const [lead] = await db.select().from(companyLeads).where(eq(companyLeads.id, draft.leadId)).limit(1);
  if (!lead) throw new NotFoundError("Lead not found.");
  const [settings] = await db.select().from(siteSettings).where(eq(siteSettings.id, 1)).limit(1);
  const identityBlockers = campaignActivationBlockReasons({
    legalName: settings?.legalCompanyName ?? null,
    businessAddress: settings ? outreachBusinessAddress(settings) : null,
    bodyTemplate: draft.body,
    requireUnsubscribePlaceholder: false,
  });
  if (identityBlockers.length) throw new AppError(identityBlockers.join(" "), 422, "campaign_activation_blocked");
  const [suppression] = await db.select({ id: sql<number>`1` }).from(companyLeads)
    .where(and(eq(companyLeads.id, lead.id), eq(companyLeads.doNotContact, true))).limit(1);
  if (suppression || ["do_not_contact", "bounced", "rejected"].includes(lead.status)) {
    throw new AppError("This lead is not eligible for outreach.", 422, "campaign_lead_blocked");
  }
  const [suppressed] = await db.select({ id: sql<number>`1` }).from(suppressedEmails)
    .where(sql`lower(${suppressedEmails.email}) = ${lead.email.toLocaleLowerCase("en")}`).limit(1);
  if (suppressed) throw new AppError("This address is on the suppression list.", 422, "campaign_lead_blocked");
  if (!z.email().safeParse(lead.email).success) throw new AppError("Lead email is invalid.", 422, "campaign_lead_blocked");
  if (lead.lastContactedAt && lead.lastContactedAt.getTime() > Date.now() - 14 * 24 * 60 * 60 * 1000) {
    throw new AppError("This lead was contacted in the last 14 days.", 422, "campaign_lead_blocked");
  }
  const [recent] = await db.select({ id: campaignMessages.id }).from(campaignMessages)
    .where(and(
      eq(campaignMessages.leadId, lead.id),
      eq(campaignMessages.status, "sent"),
      gte(campaignMessages.sentAt, new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)),
    )).limit(1);
  if (recent) throw new AppError("This lead was emailed in the last 14 days.", 422, "campaign_lead_blocked");
  const [reply] = await db.select({ id: inboxMessages.id }).from(inboxThreads)
    .innerJoin(inboxMessages, eq(inboxMessages.threadId, inboxThreads.id))
    .where(and(eq(inboxThreads.leadId, lead.id), eq(inboxMessages.direction, "inbound")))
    .limit(1);
  if (reply || lead.status === "replied") throw new AppError("This lead has replied and cannot be emailed.", 422, "campaign_lead_blocked");
  const credentials = getMailAccountCredentials().find((account) => account.id === draft.accountId);
  if (!credentials) throw new AppError(`The ${draft.accountId} sender account is not configured.`, 503);

  await db.transaction(async (tx) => {
    const [campaign] = await tx.insert(outreachCampaigns).values({
      name: `AI first email: ${lead.company}`.slice(0, 200),
      senderAccountId: draft.accountId,
      status: "active",
      subjectTemplate: draft.subject,
      bodyTemplate: draft.body,
      followupSequence: [],
      createdByUserId: admin.id,
    }).returning({ id: outreachCampaigns.id });
    if (!campaign) throw new Error("Approved draft campaign could not be created.");
    const [message] = await tx.insert(campaignMessages).values({
      campaignId: campaign.id,
      leadId: lead.id,
      step: 1,
      subject: draft.subject,
      body: draft.body,
      source: "ai",
      status: "approved",
      approvedByUserId: admin.id,
      approvedAt: new Date(),
      scheduledAt: new Date(),
      leadEmailDraftId: draft.id,
    }).returning({ id: campaignMessages.id });
    if (!message) throw new Error("Approved campaign message could not be queued.");
    await tx.update(leadEmailDrafts).set({
      status: "pending_approval",
      updatedAt: new Date(),
    }).where(eq(leadEmailDrafts.id, draft.id));
    await tx.insert(auditLogs).values({
      actorUserId: admin.id,
      actorRole: "admin",
      action: "assistant.ai_lead_draft_approved",
      entityType: "lead_email_draft",
      entityId: draft.id,
      description: "AI lead email explicitly approved by an administrator and queued for guarded delivery.",
      metadata: { campaignId: campaign.id, messageId: message.id, leadId: lead.id },
    });
  });
  revalidatePath("/admin/assistant/leads");
  revalidatePath("/admin/assistant/campaigns");
}

export async function approveLeadEmailDraftAction(formData: FormData): Promise<void> {
  return runAdminFormAction("/admin/assistant/leads", () => approveLeadDraftImpl(formData));
}

export async function getMonthToDateAiSpend(): Promise<number> {
  await requireApiAdmin();
  const month = new Date();
  month.setDate(1);
  month.setHours(0, 0, 0, 0);
  const [row] = await db.select({ total: sql<number>`coalesce(sum(${aiUsage.estimatedCostUsdMicros}), 0)::int` })
    .from(aiUsage).where(gte(aiUsage.createdAt, month));
  return row?.total ?? 0;
}
