import { NextRequest } from 'next/server';
import { handleApi } from '@/lib/errors/api-handler';
import { AppError, AppErrorCode } from '@/lib/errors/app-error';
import { getPublishedJob } from '@/lib/portal/jobs/search';

/** Route context type generated by Next.js for this dynamic segment. */
type RouteContext = { params: Promise<{ id: string }> };

/**
 * GET /api/portal/jobs/[id]
 *
 * Public detail for ONE published job. A draft, pending, closed, expired or
 * rejected job is reported as 404, so a draft cannot be probed by id.
 */
export async function GET(
  req: NextRequest,
  context: RouteContext
): Promise<Response> {
  return handleApi(req, async () => {
    // Next.js 15 delivers dynamic route params as a promise.
    const { id } = await context.params;

    // Cheap shape check before a database round-trip. A malformed id is reported
    // exactly like a missing one, so this reveals nothing.
    if (!/^[0-9a-f-]{36}$/i.test(id)) {
      throw new AppError(AppErrorCode.NOT_FOUND, 'The requested job was not found.', 404);
    }
    return getPublishedJob(id);
  });
}

