import 'server-only';
import { readFileSync } from 'fs';
import path from 'path';

/**
 * Bundled PDF typefaces.
 *
 * WHY A FONT IS COMMITTED RATHER THAN PICKED FROM THE OS:
 *
 * PDFKit's built-in "standard 14" fonts (Helvetica, Times) are WinAnsi-encoded
 * and contain NO glyph for U+20B9, the Indian Rupee sign. Every amount on this
 * platform is rupees, so an invoice or resume that renders the currency symbol
 * with a standard font produces a broken or missing character — a document that
 * looks broken precisely where a customer is checking the money.
 *
 * Relying on an OS font instead would mean the same code renders differently on
 * a developer laptop, in CI and on the production VPS, and would break outright
 * on a container with no fonts installed. Committing the two faces used here
 * makes the output byte-for-byte reproducible everywhere, and PDFKit subsets
 * embedded fonts, so only the glyphs actually used are written into the file.
 *
 * DejaVu Sans is used under the Bitstream Vera / DejaVu licence (see
 * LICENSE-DejaVu.txt beside this file). It covers Latin, Latin-1 Supplement,
 * Latin Extended-A, the general punctuation and currency blocks (including ₹),
 * and the symbols resumes and invoices actually need.
 */

export const PDF_FONT_FAMILY = 'RavelythSans';

export const PDF_FONT_REGULAR = 'body';
export const PDF_FONT_BOLD = 'bold';
export const PDF_FONT_ITALIC = 'italic';
export const PDF_FONT_SERIF = 'serif';
export const PDF_FONT_SERIF_BOLD = 'serifBold';

const FONT_FILES: Record<string, string> = {
  [PDF_FONT_REGULAR]: 'DejaVuSans.ttf',
  [PDF_FONT_BOLD]: 'DejaVuSans-Bold.ttf',
  [PDF_FONT_ITALIC]: 'DejaVuSans-Oblique.ttf',
  // A serif face is used for document titles so a resume does not look like a
  // letter from every other applicant generated by the same software.
  [PDF_FONT_SERIF]: 'DejaVuSerif.ttf',
  [PDF_FONT_SERIF_BOLD]: 'DejaVuSerif-Bold.ttf',
};

/** Absolute path to the bundled font directory. */
export function pdfFontDirectory(): string {
  return path.join(process.cwd(), 'src', 'lib', 'pdf', 'fonts');
}

const bufferCache = new Map<string, Buffer>();

/**
 * Reads a bundled font face into a Buffer, cached per process.
 *
 * Reading from disk on every document would add two synchronous reads per PDF
 * for no benefit; a server process renders many documents.
 */
export function loadPdfFont(fileName: string): Buffer {
  const cached = bufferCache.get(fileName);
  if (cached) return cached;

  const buffer = readFileSync(path.join(pdfFontDirectory(), fileName));
  bufferCache.set(fileName, buffer);
  return buffer;
}

export function pdfFontSource(weight: string): Buffer {
  return loadPdfFont(FONT_FILES[weight] ?? FONT_FILES[PDF_FONT_REGULAR]!);
}

export function hasPdfFontFile(fileName: string): boolean {
  try {
    loadPdfFont(fileName);
    return true;
  } catch {
    return false;
  }
}

/** The font faces that are actually present on disk, for diagnostics. */
export function availablePdfFonts(): string[] {
  return Object.entries(FONT_FILES)
    .filter(([, file]) => hasPdfFontFile(file))
    .map(([weight]) => weight);
}

/** True when every bundled face can actually be loaded. */
export function pdfFontsAvailable(): boolean {
  return Object.values(FONT_FILES).every((file) => hasPdfFontFile(file));
}