import { NextRequest } from 'next/server';
import { handleApi, readJsonBody } from '@/lib/errors/api-handler';
import { parseWithSchema } from '@/lib/validation/parse';
import { z } from 'zod';
import { requireAdminUser } from '@/lib/portal/auth-context';
import { setCompanyVerification } from '@/lib/portal/employers/company';

/** Route context type generated by Next.js for this dynamic segment. */
type RouteContext = { params: Promise<{ id: string }> };

const decisionSchema = z
  .object({
    status: z.enum(['verified', 'rejected', 'suspended']),
    notes: z.string().max(1000).nullish(),
  })
  .strict();

/**
 * PUT /api/portal/admin/companies/[id]
 *
 * The ONLY path that can mark a company as verified. Companies are created
 * 'pending' precisely so that an employer cannot grant itself trust, and every
 * decision here is written to the audit log.
 */
export async function PUT(
  req: NextRequest,
  context: RouteContext
): Promise<Response> {
  return handleApi(req, async () => {
    const admin = await requireAdminUser();
    const { id } = await context.params;
    const body = await readJsonBody(req);
    const input = parseWithSchema(decisionSchema, body);

    return {
      company: await setCompanyVerification({
        companyId: id,
        status: input.status,
        adminUserId: admin.id,
        notes: input.notes ?? null,
      }),
    };
  });
}
